In [2]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 10.9 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [14]:
arr=np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [15]:
arr[6]

np.int64(17)

In [18]:
print(arr[1:4])
print(arr[0:4])
print(arr[1:])



[12 13 14]
[11 12 13 14]
[12 13 14 15 16 17 18 19 20]


slice of a matrix

In [23]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
arr[5]

array([26, 27, 28, 29, 30])

In [26]:
arr[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [33]:
arr[0:5,1]

array([ 2,  7, 12, 17, 22])

Boolean Indexing

In [35]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
bool_arr=arr%2==0
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [37]:
arr=arr[bool_arr]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Arthmetic operation

In [44]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


BroadCasting

In [ ]:
arr1+10 #values of arr1 plus 10

array([11, 12, 13, 14, 15, 16])

In [46]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
arr1+arr2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

Deep and shallow copy

In [51]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [56]:
slice=slice+10
print(slice)
print(a)

[11 12 13 14 15]
[1 2 3 4 5 6 7 8 9]


In [58]:
b=a
b[0]=100
print(b)
print(a)

[100   2   3   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8   9]


In [60]:
a=np.arange(1,10)
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3   4   5   6   7   8   9]
[1 2 3 4 5 6 7 8 9]


Matrix multiplication

In [66]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(7,11).reshape(2,2)
print(a)
print(b)
print(a*b)

[[1 2]
 [3 4]]
[[ 7  8]
 [ 9 10]]
[[ 7 16]
 [27 40]]


In [63]:
print(a*b)

[[ 7 16]
 [27 40]]


In [67]:
np.dot(a,b)

array([[25, 28],
       [57, 64]])

In [68]:
print(a)
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


Advance Array Manipulation

Stacking array

In [69]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

In [70]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
np.hstack([arr1,arr2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
np.column_stack([arr1,arr2])

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

spliting Arraya

In [76]:
c=np.arange(1,7).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.hsplit(c,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [78]:
np.vsplit(c,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]