In [2]:
print("hello")

hello


In [3]:
print("world")

world


In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 7.1 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [8]:
a=[1,2,3.5,"hello"]
print(a)

[1, 2, 3.5, 'hello']


things get converted to string cause a contains a string 

In [9]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

things get converted to float beacuse there is no string in this 

In [10]:
a=[1,2,3.5]
np.array(a)

array([1. , 2. , 3.5])

In [11]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [6]:
arr=np.zeros((3,3))
arr1=np.zeros(5)
print(arr)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]


In [7]:
print(np.ones(6))
print(np.ones((6,6)))

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


linspace provides the amount of number required btw two numbers like btw 1,7 two number or 3 number etc with every element will have equal space among themselves

In [11]:
print(np.linspace(1,7,2))
print(np.linspace(1,7,5))

[1. 7.]
[1.  2.5 4.  5.5 7. ]


Random number generation

In [12]:
np.random.rand(4)

array([0.79900732, 0.63631566, 0.6133708 , 0.70519247])

In [15]:
np.random.randn(5)

array([ 0.42135064,  0.17466552,  1.082337  ,  1.50848405, -0.05369141])

In [18]:
np.random.randint(5,19,6)

array([ 5,  7, 17, 18, 12, 14])

Array Attributes

In [20]:
arr=np.array(([1,2,3],[4,5,6],[2,3,4]))
print(arr)

[[1 2 3]
 [4 5 6]
 [2 3 4]]


In [21]:
arr.size

9

In [22]:
arr.shape

(3, 3)

In [23]:
arr.dtype

dtype('int64')

Array Methods

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(6)

In [27]:
arr.sum()

np.int64(30)

In [ ]:
np.sum(arr,axis=0) #axis =0 is columnwise sum

array([ 7, 10, 13])

In [ ]:
np.sum(arr,axis=1) #axis=1 row wise sum

array([ 6, 15,  9])

In [30]:
arr.mean()

np.float64(3.3333333333333335)

In [31]:
arr.var()

np.float64(2.2222222222222223)

In [32]:
arr.std()

np.float64(1.4907119849998598)

Reshaping and resizing 

In [39]:
arr=np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [41]:
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])